[2025-01-13T02:00:58.868+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-13T02:00:58.902+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_py_v3.get_name scheduled__2025-01-11T00:00:00+00:00 [queued]>
[2025-01-13T02:00:58.914+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_py_v3.get_name scheduled__2025-01-11T00:00:00+00:00 [queued]>
[2025-01-13T02:00:58.915+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-01-13T02:00:58.937+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): get_name> on 2025-01-11 00:00:00+00:00
[2025-01-13T02:00:58.952+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_py_v3', 'get_name', 'scheduled__2025-01-11T00:00:00+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/dag_python.py', '--cfg-path', '/tmp/tmp8go9fk6o']
[2025-01-13T02:00:58.956+0000] {standard_task_runner.py:105} INFO - Job 85: Subtask get_name
[2025-01-13T02:00:58.960+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2098) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-13T02:00:58.962+0000] {standard_task_runner.py:72} INFO - Started process 2103 to run task
[2025-01-13T02:00:59.039+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_py_v3.get_name scheduled__2025-01-11T00:00:00+00:00 [running]> on host a726eb716cdf
[2025-01-13T02:00:59.193+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Khanh' AIRFLOW_CTX_DAG_ID='dag_with_py_v3' AIRFLOW_CTX_TASK_ID='get_name' AIRFLOW_CTX_EXECUTION_DATE='2025-01-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-11T00:00:00+00:00'
[2025-01-13T02:00:59.195+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-13T02:00:59.226+0000] {python.py:240} INFO - Done. Returned value was: Khanh
[2025-01-13T02:00:59.273+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-13T02:00:59.276+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_py_v3, task_id=get_name, run_id=scheduled__2025-01-11T00:00:00+00:00, execution_date=20250111T000000, start_date=20250113T020058, end_date=20250113T020059
[2025-01-13T02:00:59.344+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-13T02:00:59.396+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-13T02:00:59.401+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-13T02:03:40.493+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-13T02:03:40.524+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_py_v3.get_name scheduled__2025-01-11T00:00:00+00:00 [queued]>
[2025-01-13T02:03:40.537+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_py_v3.get_name scheduled__2025-01-11T00:00:00+00:00 [queued]>
[2025-01-13T02:03:40.538+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-01-13T02:03:40.564+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): get_name> on 2025-01-11 00:00:00+00:00
[2025-01-13T02:03:40.577+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_py_v3', 'get_name', 'scheduled__2025-01-11T00:00:00+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/dag_python.py', '--cfg-path', '/tmp/tmptk6is36_']
[2025-01-13T02:03:40.581+0000] {standard_task_runner.py:105} INFO - Job 97: Subtask get_name
[2025-01-13T02:03:40.583+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2270) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-13T02:03:40.585+0000] {standard_task_runner.py:72} INFO - Started process 2274 to run task
[2025-01-13T02:03:40.654+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_py_v3.get_name scheduled__2025-01-11T00:00:00+00:00 [running]> on host a726eb716cdf
[2025-01-13T02:03:40.790+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Khanh' AIRFLOW_CTX_DAG_ID='dag_with_py_v3' AIRFLOW_CTX_TASK_ID='get_name' AIRFLOW_CTX_EXECUTION_DATE='2025-01-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-11T00:00:00+00:00'
[2025-01-13T02:03:40.792+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-13T02:03:40.814+0000] {python.py:240} INFO - Done. Returned value was: Khanh
[2025-01-13T02:03:40.845+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-13T02:03:40.846+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_py_v3, task_id=get_name, run_id=scheduled__2025-01-11T00:00:00+00:00, execution_date=20250111T000000, start_date=20250113T020340, end_date=20250113T020340
[2025-01-13T02:03:40.885+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-13T02:03:40.927+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-13T02:03:40.930+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
