[2025-01-13T02:57:46.512+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-13T02:57:46.569+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_py_v5.get_age manual__2025-01-13T02:57:45.064956+00:00 [queued]>
[2025-01-13T02:57:46.605+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_py_v5.get_age manual__2025-01-13T02:57:45.064956+00:00 [queued]>
[2025-01-13T02:57:46.606+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-01-13T02:57:46.664+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): get_age> on 2025-01-13 02:57:45.064956+00:00
[2025-01-13T02:57:46.689+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_py_v5', 'get_age', 'manual__2025-01-13T02:57:45.064956+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/dag_python.py', '--cfg-path', '/tmp/tmp6ja0w3mc']
[2025-01-13T02:57:46.693+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=6696) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-13T02:57:46.697+0000] {standard_task_runner.py:105} INFO - Job 121: Subtask get_age
[2025-01-13T02:57:46.698+0000] {standard_task_runner.py:72} INFO - Started process 6705 to run task
[2025-01-13T02:57:47.115+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_py_v5.get_age manual__2025-01-13T02:57:45.064956+00:00 [running]> on host a726eb716cdf
[2025-01-13T02:57:47.639+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Khanh' AIRFLOW_CTX_DAG_ID='dag_with_py_v5' AIRFLOW_CTX_TASK_ID='get_age' AIRFLOW_CTX_EXECUTION_DATE='2025-01-13T02:57:45.064956+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-13T02:57:45.064956+00:00'
[2025-01-13T02:57:47.644+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-13T02:57:47.842+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-13T02:57:47.892+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-13T02:57:47.900+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_py_v5, task_id=get_age, run_id=manual__2025-01-13T02:57:45.064956+00:00, execution_date=20250113T025745, start_date=20250113T025746, end_date=20250113T025747
[2025-01-13T02:57:48.005+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-13T02:57:48.098+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-13T02:57:48.103+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
